name: context variable demo

on: workflow_dispatch

jobs:
  context-demo:
   runs-on: ubuntu-slim
   steps:
     - name: use context variables
       run: |
        echo "this workflow is triggered by ${{ github.actor }} "
        echo "the repository name is ${{ github.repository }}"
        echo " ${{github.ref_name}} "
     - name: Print all variables under github
       run: echo "${{ toJson(github)[0] }}"
   
