name: variable and secrets demo

on: workflow_dispatch

jobs:
  printVariable:
   runs-on: ubuntu-slim
   steps:
     - name: variable value
       run: |
        echo ${{ vars.my_variable}}
        echo "Variable value printed"

  printSecret:
   runs-on: ubuntu-slim
   needs: printVariable
   steps:
     - name: secret value
       run: |
        echo "Secret will not be printed on screen"
        echo "Hello!!, ${{ secrets.MY_SECRET }}"
        echo "DONE!!"

        
