name: Running Multiple Shell Commands

on: workflow_dispatch

jobs:
  multiple_shell_commands:
    runs-on: ubuntu-slim
    steps:
     - name: Commands
       run: |
         ls -la
         touch test.txt
         chmod 777 test.txt
         echo "This is one line" > test.txt
         echo "This is 2nd line" >> test.txt
         ls -la
         cat test.txt
         

