name: OR demo

on:
 push:
  branches:
    - main
    - develop
jobs:
  demo:
   runs-on: ubuntu-slim
   steps:
    - name: print the actor
      if: github.actor=='voltage-vulnerability'
      run: echo "Actor is voltage.vulnerability"
    - name: no actor
      if: github.actor!='voltage-vulnerability'
      run: echo "This is not correct actor"
